apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0...S0K
    server: https://10.38.15.84:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS...0K
    client-key-data: LS...Qo=
