---
cluster_workers:
  hosts:
    cluster_hpc_worker_1:
      ansible_host: wrk-hpc-1
    cluster_hpc_worker_2:
      ansible_host: wrk-hpc-2
    # At first support a client interface to the cluster - no mgt services required
    # cluster_mgt_worker_1:
    #   ansible_host: wrk-mgt-1

cluster:
  hosts:
    cluster_controller:
      ansible_host: ctl
  children:
    cluster_workers:
