---
cluster_workers:
  hosts:
    cluster_hpc_mgt_1:
      ansible_host: hpc-mgt-1
    cluster_hpc_wrk_1:
      ansible_host: hpc-wrk-1
    cluster_hpc_wrk_2:
      ansible_host: hpc-wrk-2

cluster:
  hosts:
    cluster_controller:
      ansible_host: ctl
  children:
    cluster_workers:
