---
cluster_compute_workers:
  hosts:
    cluster_hpc_wrk_compute_1:
      ansible_host: hpc-wrk-compute-1
    cluster_hpc_wrk_compute_2:
      ansible_host: hpc-wrk-compute-2

cluster_system_workers:
  hosts:
    cluster_hpc_wrk_system_1:
      ansible_host: hpc-wrk-system-1

cluster_workers:
  children:
    cluster_compute_workers:
    cluster_system_workers:

cluster:
  hosts:
    cluster_controller:
      ansible_host: ctl
  children:
    cluster_workers:
