---
- name: Job - Shell Display
  hosts: cluster_controller
  become: false
  vars:
    pod_name: "test-shell"
  tasks:
    - name: Get all pods across all namespaces
      ansible.builtin.command:
        cmd: kubectl get pods --all-namespaces
      environment:
        KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"
      register: pods_output
      changed_when: false

    - name: Display pods
      ansible.builtin.debug:
        var: pods_output.stdout_lines

    - name: Describe pod {{ pod_name }}
      ansible.builtin.command:
        cmd: kubectl describe pod {{ pod_name }}
      environment:
        KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"
      register: describe_output
      changed_when: false

    - name: Print pod description
      ansible.builtin.debug:
        msg: "{{ describe_output.stdout_lines }}"

    - name: Run action menu
      ansible.builtin.include_tasks: ../../tasks/display_menu.yaml
