apiScheme: "https"
homeportScheme: "https"

postgresql:
  enabled: true

rabbitmq:
  enabled: true

nodeSelector:
  cmyk.io/node-type: management

tolerations:
  - key: "cmyk.io/management-only"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
