---
- name: Prompt for action
  ansible.builtin.pause:
    prompt: |
      Choose an action:
        logs (l)   - Show job logs
        delete (d) - Delete job
        exit (e)   - Exit
  register: _action_input
  until: _action_input.user_input | lower in ['logs', 'l', 'delete', 'd', 'exit', 'e']
  retries: 5
  delay: 0

- name: Get logs {{ pod_name }}
  ansible.builtin.command:
    cmd: kubectl logs {{ pod_name }}
  environment:
    KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"
  register: _logs_again
  changed_when: false
  when: _action_input.user_input | lower in ['logs', 'l']

- name: Print job logs
  ansible.builtin.debug:
    msg: "{{ _logs_again.stdout_lines }}"
  when: _action_input.user_input | lower in ['logs', 'l']

- name: Delete job {{ pod_name }}
  ansible.builtin.command:
    cmd: kubectl delete pod {{ pod_name }}
  environment:
    KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"
  changed_when: true
  when: _action_input.user_input | lower in ['delete', 'd']

- name: Return to action menu
  ansible.builtin.include_tasks: display_menu.yaml
  when: _action_input.user_input | lower in ['logs', 'l']
