---
- name: Check - K8s Nodes
  hosts: cluster_controller
  become: false
  tasks:
    - name: Describe all nodes
      ansible.builtin.command:
        cmd: kubectl describe nodes
      environment:
        KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"
      register: nodes_output
      changed_when: false

    - name: Display nodes
      ansible.builtin.debug:
        var: nodes_output.stdout_lines
