---
- name: Check - K8s Nodes Container Stats
  hosts: cluster
  become: true
  tasks:
    - name: Get container stats
      ansible.builtin.command:
        cmd: bash -c "crictl stats | sed 's/\\x1b\\[[0-9;]*[A-Za-z]//g'"
      register: crictl_stats_output
      changed_when: false

    - name: Display container stats
      ansible.builtin.debug:
        msg: "{{ crictl_stats_output.stdout_lines }}"
